#!/usr/bin/env python3
"""
Operator console dev server.

Reads GIBBERLY_BACKEND from the environment (or ../.env) and writes
config.js before starting a local HTTP server.

Usage:
  cd ~/gibberly
  python3 operator/serve.py
  # or override the backend URL inline:
  GIBBERLY_BACKEND=wss://gibberly-backend.azurewebsites.net python3 operator/serve.py
"""
import http.server
import os
import pathlib

# Load ../.env if present (simple key=value parser, no extra dependencies)
env_file = pathlib.Path(__file__).parent.parent / ".env"
if env_file.exists():
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, val = line.partition("=")
            os.environ.setdefault(key.strip(), val.strip())

backend = os.environ.get("GIBBERLY_BACKEND", "ws://localhost:8000")
port = int(os.environ.get("OPERATOR_PORT", "9000"))

config_js = pathlib.Path(__file__).parent / "config.js"
config_js.write_text(
    f"// Auto-generated by serve.py — edit GIBBERLY_BACKEND in .env, not this file.\n"
    f'window.GIBBERLY_BACKEND = "{backend}";\n'
)
print(f"config.js written: GIBBERLY_BACKEND={backend}")

os.chdir(pathlib.Path(__file__).parent)
print(f"Serving operator console at http://localhost:{port}")
http.server.test(
    HandlerClass=http.server.SimpleHTTPRequestHandler,
    port=port,
    bind="localhost",
)
